# -*- coding: utf-8 -*-
"""Projeto 1 - Desenvolvimento Game - 3.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H9PNM_jklxEkfhk8O2Orxt4fF3HtQoGZ
"""

# Import
import random
from os import system, name

import pandas as pd

# Função que desenha a forca na tela
def display_hangman(chances):

  # Lista de estágios da forca
  stages =  [ # estágio 6 (final)
             '''
              ________
             |        |
             |        O
             |       \|/
             |        |
             |       / \\
             -
             ''',
             # estágio 5
             '''
              ________
             |        |
             |        O
             |       \|/
             |        |
             |       /
             -
             ''',
             # estágio 4
             '''
              ________
             |        |
             |        O
             |       \|/
             |        |
             |
             -
             ''',
             # estágio 3
             '''
              ________
             |        |
             |        O
             |       \|
             |        |
             |
             -
             ''',
             # estágio 2
             '''
              ________
             |        |
             |        O
             |        |
             |        |
             |
             -
             ''',
             # estágio 1
             '''
              ________
             |        |
             |        O
             |
             |
             |
             -
             ''',
             # estágio 0
             '''
              ________
             |        |
             |
             |
             |
             |
             -
             '''
            ]

  return stages[min(chances, 7)]

# Função do jogo
def game():

    print("\nBem-vindo(a) ao jogo da forca!")
    print("Frutas, verduras ou legumes")
    print("Adivinhe a palavra abaixo:\n")

    # Lista de palavras para o jogo
    url = 'https://raw.githubusercontent.com/tarcilaalvess/Data_Analysis_Python/main/Hangman_Project/Data/lista-pt.csv'

    palavras = pd.read_csv(url, encoding='latin1', header=None)

    # Converte a coluna para lista
    palavras = palavras[0].tolist()

    # Escolha randômica da palavra
    palavra = random.choice(palavras)

    # Lista  de letras  da palavra
    lista_letras_palavras = [letra for letra in palavra]

    # List comprehension (tabuleiro)
    letras_descobertas = ['_' for letra in palavra]

    # Número de chances
    chances = 6

    # Lista para as letras digitadas
    letras_tentativas = []

    # Lista para as letras erradas
    letras_erradas = []

    # Loop enquanto número de chances for maior do que zero
    while chances > 0:

        # Print
        print(display_hangman(chances))
        print(" ".join(letras_descobertas))
        print("\nChances restantes:", chances)
        print("Letras erradas:", " ".join(letras_erradas))

        # Tentativa
        while True:
          tentativa = input("\nDigite uma letra: ").lower()

          #Verifica se o input é uma única letra sem acento
          if not tentativa.isalpha():
            print("Digite uma letra válida (sem números, acentos ou caracteres especiais).")
            continue

          if len(tentativa) != 1:
            print("Digite apenas uma letra por vez.")
            continue

          # Condicional
          if tentativa in letras_tentativas:
            print("\nVocê já tentou esta letra. Escolha outra!")
            continue

          break

        #Lista de tentativas (letras)
        letras_tentativas.append(tentativa)

        # Condicional
        if tentativa in lista_letras_palavras:
            index = 0
            print ("Você acertou a letra!")

            # Loop
            for letra in lista_letras_palavras:

              #Condicional
                if tentativa == letra:
                    letras_descobertas[index] = letra
                index += 1

        # Decremento
        else:
            chances -= 1
            letras_erradas.append(tentativa)

        # Se todos os espaços foram preenchidos, o jogo acabou
        if "_" not in letras_descobertas:
            print("\nVocê venceu, a palavra era:", palavra)
            print(display_hangman(chances))
            print(" ".join(letras_descobertas))
            break

    # Condicional
    if "_" in letras_descobertas:
        chances = 0
        print("\nVocê perdeu, a palavra era:", palavra)
        print(display_hangman(chances))
        print(" ".join(letras_descobertas))
        print("Letras erradas:", " ".join(letras_erradas))


# Bloco main
if __name__ == "__main__":
    game()